const phoneticData = {
    // Eläimet
    dog: '/dɔːɡ/',
    cat: '/kæt/',
    bird: '/bɜːrd/',
    fish: '/fɪʃ/',
    horse: '/hɔːrs/',
    cow: '/kaʊ/',
    pig: '/pɪɡ/',
    sheep: '/ʃiːp/',
    mouse: '/maʊs/',
    bear: '/beər/',
    rabbit: '/ræbɪt/',
    tiger: '/taɪɡər/',
    
    // Värit
    red: '/red/',
    blue: '/bluː/',
    yellow: '/jeloʊ/',
    green: '/ɡriːn/',
    orange: '/ɔːrɪndʒ/',
    purple: '/pɜːrpəl/',
    black: '/blæk/',
    white: '/waɪt/',
    gray: '/ɡreɪ/',
    brown: '/braʊn/',
    pink: '/pɪŋk/',
    
    // Numerot
    zero: '/zɪroʊ/',
    one: '/wʌn/',
    two: '/tuː/',
    three: '/θriː/',
    four: '/fɔːr/',
    five: '/faɪv/',
    six: '/sɪks/',
    seven: '/sevən/',
    eight: '/eɪt/',
    nine: '/naɪn/',
    ten: '/ten/',
    
    // Ruoka
    apple: '/æpəl/',
    banana: '/bəˈnænə/',
    bread: '/bred/',
    milk: '/mɪlk/',
    cheese: '/tʃiːz/',
    chicken: '/tʃɪkən/',
    rice: '/raɪs/',
    carrot: '/kærət/',
    tomato: '/təˈmeɪtoʊ/',
    potato: '/pəˈteɪtoʊ/',
    strawberry: '/stroːberi/',
    
    // Perhe
    mother: '/mʌðər/',
    father: '/fɑːðər/',
    brother: '/brʌðər/',
    sister: '/sɪstər/',
    grandmother: '/ɡrænmʌðər/',
    grandfather: '/ɡrænfɑːðər/',
    baby: '/beɪbi/',
    family: '/fæməli/',
    uncle: '/ʌŋkəl/',
    aunt: '/ænt/',
    cousin: '/kʌzən/',
    
    // Koulu
    school: '/skuːl/',
    teacher: '/tiːtʃər/',
    book: '/bʊk/',
    pen: '/pen/',
    pencil: '/pensəl/',
    eraser: '/ɪreɪsər/',
    backpack: '/bækpæk/',
    desk: '/desk/',
    board: '/bɔːrd/',
    paper: '/peɪpər/',
    scissors: '/sɪzərz/',
    glue: '/ɡluː/',
    
    // Keho
    head: '/hed/',
    hand: '/hænd/',
    foot: '/fʊt/',
    eye: '/aɪ/',
    ear: '/ɪr/',
    nose: '/noʊz/',
    mouth: '/maʊθ/',
    teeth: '/tiːθ/',
    hair: '/her/',
    finger: '/fɪŋɡər/',
    stomach: '/stʌmək/',
    
    // Vaatteet
    shirt: '/ʃɜːrt/',
    pants: '/pænts/',
    dress: '/dres/',
    jacket: '/dʒækət/',
    shoes: '/ʃuːz/',
    socks: '/sɑːks/',
    hat: '/hæt/',
    gloves: '/ɡlʌvz/',
    scarf: '/skɑːrf/',
    shorts: '/ʃɔːrts/',
    skirt: '/skɜːrt/'
};

const learningTips = {
    // Eläimet
    dog: 'Muistisääntö: Koira sanoo "woof" - dog! 🐕',
    cat: 'Lyhyt sana kuten "kissa" suomeksi. Cats say meow! 🐱',
    bird: 'Lintu lentää - bird flies high in the sky! 🐦',
    fish: 'Kala ui vedessä - fish swim in water! 🐟',
    horse: 'Hevonen juoksee - horses gallop fast! 🐎',
    cow: 'Lehmä sanoo "moo" - cow says moo! 🐄',
    pig: 'Sika on vaaleanpunainen - pigs are pink! 🐷',
    sheep: 'Lammas antaa villaa - sheep give wool! 🐑',
    mouse: 'Hiiri on pieni - mouse is small! 🐭',
    bear: 'Karhu on iso - bear is big and strong! 🐻',
    rabbit: 'Jänis hyppii - rabbits hop around! 🐰',
    tiger: 'Tiikeri on raidallinen - tigers have stripes! 🐅',
    
    // Värit
    red: 'Punainen kuin tomaatti - red like a tomato! 🍅',
    blue: 'Sininen kuin taivas - blue like the sky! 💙',
    yellow: 'Keltainen kuin aurinko - yellow like the sun! ☀️',
    green: 'Vihreä kuin ruoho - green like grass! 🌱',
    orange: 'Oranssi kuin appelsiini - orange like... orange! 🍊',
    purple: 'Violetti kuin kukkanen - purple like a flower! 💜',
    black: 'Musta kuin yö - black like the night! 🖤',
    white: 'Valkoinen kuin lumi - white like snow! ❄️',
    gray: 'Harmaa kuin pilvet - gray like clouds! ☁️',
    brown: 'Ruskea kuin puu - brown like wood! 🤎',
    pink: 'Pinkki kuin flamingo - pink like a flamingo! 🦩',
    
    // Numerot
    zero: 'Nolla - ei mitään! Round like an egg! 🥚',
    one: 'Yksi sormi ylös - one finger up! ☝️',
    two: 'Kaksi silmää - two eyes to see! 👀',
    three: 'Kolme kolikkoa - three coins! 🪙',
    four: 'Neljä tuolin jalkaa - four chair legs! 🪑',
    five: 'Viisi sormea kädessä - five fingers! ✋',
    six: 'Kuusi kuukautta - six months! 📅',
    seven: 'Seitsemän väriä sateenkaaressa - seven rainbow colors! 🌈',
    eight: 'Kahdeksan jalkaa hämähäkillä - eight spider legs! 🕷️',
    nine: 'Yhdeksän kuukautta raskaus - nine months pregnancy! 🤰',
    ten: 'Perfect ten - täydet pisteet! ⭐',
    
    // Ruoka  
    apple: 'Omena päivässä pitää lääkärin loitolla! 🍎',
    banana: 'Banaani on keltainen ja kaarevan muotoinen! 🍌',
    bread: 'Leipä on peruskauraa - bread is basic food! 🍞',
    milk: 'Maito tulee lehmältä - milk comes from cows! 🥛',
    cheese: 'Juusto on hiirien herkkua - mice love cheese! 🧀',
    chicken: 'Kana munii munia - chickens lay eggs! 🐔',
    rice: 'Riisi on pientä ja valkoista - rice is small and white! 🍚',
    carrot: 'Porkkana on oranssi ja terveellinen! 🥕',
    tomato: 'Tomaatti on punainen ja mehevä! 🍅',
    potato: 'Peruna kasvaa maassa - potatoes grow underground! 🥔',
    strawberry: 'Mansikka on makea ja punainen! 🍓',
    
    // Perhe
    mother: 'Äiti on rakas - mother is loving! 👩',
    father: 'Isä on vahva - father is strong! 👨',
    brother: 'Veli leikkii kanssani - brother plays with me! 👦',
    sister: 'Sisko jakaa leluja - sister shares toys! 👧',
    grandmother: 'Isoäiti leipoo keksejä - grandma bakes cookies! 👵',
    grandfather: 'Isoisä kertoo tarinoita - grandpa tells stories! 👴',
    baby: 'Vauva on pieni ja söpö - baby is small and cute! 👶',
    family: 'Perhe on tärkeä - family is important! 👨‍👩‍👧‍👦',
    uncle: 'Setä on isän veli - uncle is dad\'s brother! 👨',
    aunt: 'Täti on äidin sisko - aunt is mom\'s sister! 👩',
    cousin: 'Serkku on tädin lapsi - cousin is aunt\'s child! 👫',
    
    // Koulu
    school: 'Koulussa opitaan uutta - we learn new things at school! 🏫',
    teacher: 'Opettaja opettaa meille - teacher teaches us! 👩‍🏫',
    book: 'Kirjassa on tarinoita - books have stories! 📚',
    pen: 'Kynä kirjoittaa sinistä - pen writes in blue! 🖊️',
    pencil: 'Lyijykynä voi pyyhkiä - pencil can be erased! ✏️',
    eraser: 'Pyyhekumi poistaa virheet - eraser removes mistakes! 🧽',
    backpack: 'Repussa on koulutarvikkeita - backpack holds school supplies! 🎒',
    desk: 'Pulpetissa tehdään töitä - we work at the desk! 🪑',
    board: 'Taululle kirjoitetaan - we write on the board! 📋',
    paper: 'Paperille piirretään - we draw on paper! 📄',
    scissors: 'Saksilla leikataan - scissors cut things! ✂️',
    glue: 'Liimalla liimataan - glue sticks things together! 🧴',
    
    // Keho
    head: 'Päässä on aivot - brain is in the head! 👤',
    hand: 'Kädellä tartutaan - we grab things with hands! ✋',
    foot: 'Jalalla kävellään - we walk with feet! 🦶',
    eye: 'Silmällä nähdään - we see with eyes! 👁️',
    ear: 'Korvalla kuullaan - we hear with ears! 👂',
    nose: 'Nenällä haistaan - we smell with nose! 👃',
    mouth: 'Suulla syödään - we eat with mouth! 👄',
    teeth: 'Hampaat purtavat ruokaa - teeth bite food! 🦷',
    hair: 'Hiukset kasvavat päässä - hair grows on head! 💇',
    finger: 'Sormilla tartutaan - we grab with fingers! 👆',
    stomach: 'Vatsassa sulaa ruoka - food digests in stomach! 🤰',
    
    // Vaatteet
    shirt: 'Paita peittää ylävartalon - shirt covers upper body! 👔',
    pants: 'Housut peittävät jalat - pants cover legs! 👖',
    dress: 'Mekko on tytön vaate - dress is for girls! 👗',
    jacket: 'Takki lämmittää - jacket keeps you warm! 🧥',
    shoes: 'Kengät suojaavat jalkoja - shoes protect feet! 👟',
    socks: 'Sukat lämmittävät jalkoja - socks warm your feet! 🧦',
    hat: 'Hattu suojaa päätä - hat protects your head! 🎩',
    gloves: 'Hanskat lämmittävät käsiä - gloves warm your hands! 🧤',
    scarf: 'Huivi lämmittää kaulaa - scarf warms your neck! 🧣',
    shorts: 'Shortsit ovat lyhyet housut - shorts are short pants! 🩳',
    skirt: 'Hame on tytön vaate - skirt is for girls! 👗'
};

const wordDatabase = {
    animals: [
        { finnish: "koira", english: "dog", emoji: "🐕", difficulty: "easy" },
        { finnish: "kissa", english: "cat", emoji: "🐈", difficulty: "easy" },
        { finnish: "lintu", english: "bird", emoji: "🐦", difficulty: "medium" },
        { finnish: "kala", english: "fish", emoji: "🐟", difficulty: "easy" },
        { finnish: "hevonen", english: "horse", emoji: "🐴", difficulty: "medium" },
        { finnish: "lehmä", english: "cow", emoji: "🐄", difficulty: "easy" },
        { finnish: "sika", english: "pig", emoji: "🐷", difficulty: "easy" },
        { finnish: "lammas", english: "sheep", emoji: "🐑", difficulty: "medium" },
        { finnish: "hiiri", english: "mouse", emoji: "🐭", difficulty: "easy" },
        { finnish: "karhu", english: "bear", emoji: "🐻", difficulty: "easy" },
        { finnish: "jänis", english: "rabbit", emoji: "🐰", difficulty: "hard" },
        { finnish: "tiikeri", english: "tiger", emoji: "🐅", difficulty: "hard" }
    ],
    colors: [
        { finnish: "punainen", english: "red", emoji: "🔴", difficulty: "easy" },
        { finnish: "sininen", english: "blue", emoji: "🔵", difficulty: "easy" },
        { finnish: "keltainen", english: "yellow", emoji: "🟡", difficulty: "medium" },
        { finnish: "vihreä", english: "green", emoji: "🟢", difficulty: "easy" },
        { finnish: "oranssi", english: "orange", emoji: "🟠", difficulty: "medium" },
        { finnish: "violetti", english: "purple", emoji: "🟣", difficulty: "hard" },
        { finnish: "musta", english: "black", emoji: "⚫", difficulty: "easy" },
        { finnish: "valkoinen", english: "white", emoji: "⚪", difficulty: "easy" },
        { finnish: "harmaa", english: "gray", emoji: "🩶", difficulty: "medium" },
        { finnish: "ruskea", english: "brown", emoji: "🟤", difficulty: "medium" },
        { finnish: "pinkki", english: "pink", emoji: "🩷", difficulty: "easy" }
    ],
    numbers: [
        { finnish: "yksi", english: "one", emoji: "1️⃣" },
        { finnish: "kaksi", english: "two", emoji: "2️⃣" },
        { finnish: "kolme", english: "three", emoji: "3️⃣" },
        { finnish: "neljä", english: "four", emoji: "4️⃣" },
        { finnish: "viisi", english: "five", emoji: "5️⃣" },
        { finnish: "kuusi", english: "six", emoji: "6️⃣" },
        { finnish: "seitsemän", english: "seven", emoji: "7️⃣" },
        { finnish: "kahdeksan", english: "eight", emoji: "8️⃣" },
        { finnish: "yhdeksän", english: "nine", emoji: "9️⃣" },
        { finnish: "kymmenen", english: "ten", emoji: "🔟" },
        { finnish: "nolla", english: "zero", emoji: "0️⃣" }
    ],
    food: [
        { finnish: "omena", english: "apple", emoji: "🍎" },
        { finnish: "banaani", english: "banana", emoji: "🍌" },
        { finnish: "leipä", english: "bread", emoji: "🍞" },
        { finnish: "maito", english: "milk", emoji: "🥛" },
        { finnish: "juusto", english: "cheese", emoji: "🧀" },
        { finnish: "kana", english: "chicken", emoji: "🍗" },
        { finnish: "riisi", english: "rice", emoji: "🍚" },
        { finnish: "porkkana", english: "carrot", emoji: "🥕" },
        { finnish: "tomaatti", english: "tomato", emoji: "🍅" },
        { finnish: "peruna", english: "potato", emoji: "🥔" },
        { finnish: "mansikka", english: "strawberry", emoji: "🍓" },
        { finnish: "appelsiini", english: "orange", emoji: "🍊" }
    ],
    family: [
        { finnish: "äiti", english: "mother", emoji: "👩" },
        { finnish: "isä", english: "father", emoji: "👨" },
        { finnish: "veli", english: "brother", emoji: "👦" },
        { finnish: "sisko", english: "sister", emoji: "👧" },
        { finnish: "isoäiti", english: "grandmother", emoji: "👵" },
        { finnish: "isoisä", english: "grandfather", emoji: "👴" },
        { finnish: "vauva", english: "baby", emoji: "👶" },
        { finnish: "perhe", english: "family", emoji: "👨‍👩‍👧‍👦" },
        { finnish: "setä", english: "uncle", emoji: "👨" },
        { finnish: "täti", english: "aunt", emoji: "👩" },
        { finnish: "serkku", english: "cousin", emoji: "👫" }
    ],
    school: [
        { finnish: "koulu", english: "school", emoji: "🏫" },
        { finnish: "opettaja", english: "teacher", emoji: "👩‍🏫" },
        { finnish: "kirja", english: "book", emoji: "📚" },
        { finnish: "kynä", english: "pen", emoji: "🖊️" },
        { finnish: "lyijykynä", english: "pencil", emoji: "✏️" },
        { finnish: "pyyhekumi", english: "eraser", emoji: "🧽" },
        { finnish: "reppu", english: "backpack", emoji: "🎒" },
        { finnish: "pulpetti", english: "desk", emoji: "🪑" },
        { finnish: "taulu", english: "board", emoji: "📋" },
        { finnish: "paperi", english: "paper", emoji: "📄" },
        { finnish: "sakset", english: "scissors", emoji: "✂️" },
        { finnish: "liima", english: "glue", emoji: "🧴" }
    ],
    body: [
        { finnish: "pää", english: "head", emoji: "👤" },
        { finnish: "käsi", english: "hand", emoji: "✋" },
        { finnish: "jalka", english: "foot", emoji: "🦶" },
        { finnish: "silmä", english: "eye", emoji: "👁️" },
        { finnish: "korva", english: "ear", emoji: "👂" },
        { finnish: "nenä", english: "nose", emoji: "👃" },
        { finnish: "suu", english: "mouth", emoji: "👄" },
        { finnish: "hampaat", english: "teeth", emoji: "🦷" },
        { finnish: "hiukset", english: "hair", emoji: "💇" },
        { finnish: "sormi", english: "finger", emoji: "👆" },
        { finnish: "vatsa", english: "stomach", emoji: "🤰" }
    ],
    clothes: [
        { finnish: "paita", english: "shirt", emoji: "👔" },
        { finnish: "housut", english: "pants", emoji: "👖" },
        { finnish: "mekko", english: "dress", emoji: "👗" },
        { finnish: "takki", english: "jacket", emoji: "🧥" },
        { finnish: "kengät", english: "shoes", emoji: "👟" },
        { finnish: "sukat", english: "socks", emoji: "🧦" },
        { finnish: "hattu", english: "hat", emoji: "🎩" },
        { finnish: "hanskat", english: "gloves", emoji: "🧤" },
        { finnish: "huivi", english: "scarf", emoji: "🧣" },
        { finnish: "shortsit", english: "shorts", emoji: "🩳" },
        { finnish: "hame", english: "skirt", emoji: "👗" }
    ]
};